### ISSUE TITLE
ask for maintainer

### ISSUE THREAD

**Issue by chirag04** [AvianFlu/ntwitter#106]
@AvianFlu : This is a great project and a lot more people are trying to use this. However i think you are not able to maintain it. It makes sense to ask for maintainer.

**Comment by chirag04** [comment]
@passcod is the best fit i think

**Comment by passcod** [comment]
My "once-was" fork ([__m__twitter](/passcod/mtwitter)) is more of a work of its own now, bearing little resemblance to this original. I maintain it in my spare time, and I'm fairly quick at fixing things at the moment, as well as for the foreseeable future. I am not, however, interested in maintaining __n__twitter.

**Comment by chirag04** [comment]
i think i will use twit library.
