### ISSUE TITLE
Add additional collaborators?

### ISSUE THREAD

**Issue by technicalpickles** [AvianFlu/ntwitter#124]
There haven't been any updates in about a year, and there's some pretty severe bugs including Twitter's v1 API being sunsetted which makes ntwitter unusable (see https://github.com/AvianFlu/ntwitter/issues/110). I've been using @sebhildebrandt's fork in the interim which includes (I don't see a PR though).

Are you open to adding collaborators to this repository and to the npm package? 

Or another alternative would be to indicate in the README and description it's not being maintained, and suggest alternatives.

/cc @AvianFlu @jdub

**Comment by j127** [comment]
+1

**Comment by kevinohara80** [comment]
+1000

**Comment by kirkkohler** [comment]
maybe the top pull request/contributors should create an organization yet again fork ntwitter to yet another fork but with more activity?

**Comment by kirkkohler** [comment]
doing some searching. there are some branched projects that are a little more updated.  Such as mtwitter for streaming, etc.  good luck out there.

**Comment by sebhildebrandt** [comment]
I also was thinking to rewrite a package. Maybe I have some time next month. Will inform you then. 

Sebastian Hildebrandt
