### ISSUE TITLE
Support node 0.5.x

### ISSUE THREAD

**Issue by abh** [AvianFlu/ntwitter#13]
Allow ntwitter to install via npm under node 0.5.x.

**Comment by AvianFlu** [comment]
Can you tell me anything about how it fails?  I'll definitely be updating this library, especially since 0.6.x is right around the corner, but I won't be able to do proper testing of my own until this weekend.  Any information you, or anyone else, can share, will be very helpful.

**Comment by AvianFlu** [comment]
Try `ntwitter@0.2.7-2`.  I changed the `engines` field in the package.json.  This will stop `npm` from yelling at you, but there may be other compatibility issues.

**Comment by abh** [comment]
Thanks!  I'll let you know if I run into any problems.

**Comment by AvianFlu** [comment]
I've been running `ntwitter` on node 0.5.10 for a day or two now with no problems - I'm closing this unless an issue comes up.
