### ISSUE TITLE
streaming support for limit and delete kind of tweets

### ISSUE THREAD

**Issue by masterkain** [AvianFlu/ntwitter#14]
Hello,

I'm not sure, but has this functionality been stripped?
https://github.com/technoweenie/twitter-node/blob/master/lib/twitter-node/index.js#L196

Because it's actually useful.

Cheers

**Comment by AvianFlu** [comment]
There's a lot of development hours in between technoweenie's project and the codebase I maintain - most of them not mine.  I can't say when or why it got stripped, but I agree, it should be added back.  

I'll have a look at this later today.

**Comment by AvianFlu** [comment]
`ntwitter@0.2.8` has been published, and those events should now fire in the same way they did.  Please test it and let me know - there have been internal API changes since twitter-node, and I had to adapt the code a little.

**Comment by masterkain** [comment]
Appears to be working, thanks!

From Twitter docs there are also "scrub_geo" messages, although rare.

**Comment by masterkain** [comment]
Oh, forget about it, just saw: https://github.com/AvianFlu/ntwitter/commit/f0e7b6777f6944d94988ec342f38fbe554af8f95
