### ISSUE TITLE
REST Get returns null to callback?

### ISSUE THREAD

**Issue by yono38** [AvianFlu/ntwitter#24]
Why  is line 105 of twitter.js:
`callback(null, json);`

Shouldn't is just be callback(json)? If you have a reason for this, you should probably outline it in the Readme, I had to read through the code to figure out why I was getting null results in my callback.

**Comment by AvianFlu** [comment]
The first argument is, by Node.js convention, always reserved for a possible error.  This allows you to do stuff like this:

``` js

function callback(err, data) {
  if (err) {
    // by returning here, we prevent the function from continuing on error
    return doSomethingWith(err);
  }
  // if there's no error, move on and use the other parameter.
  gotData(data);
}
```

This is much simpler than having to look at the object returned to inspect its properties to determine whether or not it's an error.
