### ISSUE TITLE
remove console.log calls wrapping console.dir

### ISSUE THREAD

**Issue by Prinzhorn** [AvianFlu/ntwitter#25]
I copied the code for the user streams using "track":

``` js
stream.on('data', function (data) {
    console.log(console.dir(data));
});
```

Besides the tweets this code also outputs some "undefined"s on my console.

I'm using node 0.6.6

Edit: I'm sorry for confusing you. The cause is of course that console.dir already outputs to console and returns undefined.

**You should remove all occurrences of `console.log(console.dir(foo));` with `console.dir(foo);` in the example codes.**

**Comment by AvianFlu** [comment]
Fixed.  Thanks for pointing this out.
