### ISSUE TITLE
Filtering by "track" and "locations" isn't filtering properly

### ISSUE THREAD

**Issue by nhunzaker** [AvianFlu/ntwitter#27]
I've got the following settings:

``` js
twitter.stream('statuses/filter', { 

    track      : "pizza",
    locations  : '-150.75,0, -60,90'

}, function(stream) {

    stream.on('data', function (tweet) {
        // do stuff
    }); 

});

```

Is the error between my keyboard and monitor, or is something else going on?

**Comment by AvianFlu** [comment]
I believe that the parameters always need to be arrays.  In other words,

```
 track: [ 'pizza', 'beer' ],
 locations: [ '150.75,0, -60,90' ]
```

Let me know if this helps.  The docs may need updating.

**Comment by nhunzaker** [comment]
Well,

Aside from that throwing an error (I believe due to the location value), when I filter by these parameters:

```
track      : ["beer", "pizza" ],
locations  : ['-180,0, 180,90']
```

It doesn't appear as if beer or pizza are relavent to any of the tweets returned. Do you think this is just a limitation of the API?

**Comment by AvianFlu** [comment]
It could be.  Try a `user` stream - `statuses/filter` has some limitations to it, although I don't recall if they apply here.

**Comment by impronunciable** [comment]
From the twitter Streaming API docs: 

> A locations parameter may be combined with track parameters, but note that all terms are logically ORd, so the query ? 
> string track=twitter&amp;amp;locations=-122.75,36.8,-121.75,37.8 would match any tweets containing the term Twitter
> (even non-geo tweets) OR coming from the San Francisco area.

Because of the logical OR between your tracked keywords and the huge area you are covering it makes your query look nearly like the "statuses/sample" method

**Comment by nhunzaker** [comment]
Fair enough. I think this more or less answers my problem. Thanks for the clarification!

**Comment by impronunciable** [comment]
Great. Sorry for my awful and painful English.

**Comment by nhunzaker** [comment]
The thought didn't even cross my mind!
