### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by optikfluffel** [AvianFlu/ntwitter#58]
Hi girls 'n guys, I'm having some `[Error: socket hang up] code: 'ECONNRESET'` over here when trying to get the Favorites of about 280 Users at Heroku. Do you have a clue what's happening there? xD

Thanks :)

**Comment by fent** [comment]
Twitter does that when you request too often. Yeah it sucks. You can limit your requests to a few per second to lessen the errors.

**Comment by optikfluffel** [comment]
oh ok.. Thanks :)

**Comment by dougalcampbell** [comment]
I've been having this issue when I loop over a list of IDs, fetching many batches of user info. I'm going to look at using kriskowal/q to make the calls synchronously. Just hoping it doesn't happen at a deeper level in ntwitter, like in the _getUsingCursor() calls.
