### ISSUE TITLE
App crash randomly on... event.emit

### ISSUE THREAD

**Issue by gabrielstuff** [AvianFlu/ntwitter#68]
Hi there,

I've got this very simple app :

```
var twitter = require('ntwitter');
var credentials = require('./credentials.js');
var http = require('http');
var port = process.env.PORT || 5000;

var httpServer = http.createServer(function (request, response) {
  request.addListener('end', function () {
            clientFiles.serve(request, response);
        });
}).listen(port);

var io = require('socket.io').listen(httpServer);

var new_tweet = {};

var t = new twitter({
    consumer_key: credentials.consumer_key,
    consumer_secret: credentials.consumer_secret,
    access_token_key: credentials.access_token_key,
    access_token_secret: credentials.access_token_secret
});
io.sockets.on('connection', function (socket) {
    t.stream(
        'statuses/filter',
        { track: ['awesome', 'cool', 'rad', 'gnarly', 'groovy'] },
        function(stream) {
            stream.on('data', function(tweet) {
                //console.log(tweet.text);
                new_tweet = tweet.text;
                socket.emit('new_tweet', new_tweet);
            });
        }
    );
});
```

Well anyone can tried it, quiet simple and straightforward. The thing is that sometime it crashes, and I do not get why ??

The log error is : 

```
11:55:32 web.1     | events.js:68
11:55:32 web.1     |         throw new Error("Uncaught, unspecified 'error' event.");
11:55:32 web.1     |               ^
11:55:32 web.1     | Error: Uncaught, unspecified 'error' event.
11:55:32 web.1     |     at EventEmitter.emit (events.js:68:15)
11:55:32 web.1     |     at ClientRequest.Twitter.stream (/usr/local/lib/node_modules/ntwitter/lib/twitter.js:251:14)
11:55:32 web.1     |     at ClientRequest.EventEmitter.emit (events.js:88:17)
11:55:32 web.1     |     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1455:7)
11:55:32 web.1     |     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
11:55:32 web.1     |     at CleartextStream.socketOnData [as ondata] (http.js:1366:20)
11:55:32 web.1     |     at CleartextStream.CryptoStream._push (tls.js:495:27)
11:55:32 web.1     |     at SecurePair.cycle (tls.js:849:20)
11:55:32 web.1     |     at EncryptedStream.CryptoStream.write (tls.js:230:13)
11:55:32 web.1     |     at Socket.ondata (stream.js:38:26)
11:55:32 web.1     | process terminated
11:55:32 system    | sending SIGTERM to all processes
```

Here is the package.json file for those of you who would like to try :

```
{ 
    "name": "Twitter.stream.ringthebell.io",
    "description": "Twitter server allowing to fetch the twitter stream API and push to a javascript client",
    "version": "0.0.1",
    "dependencies": { 
        "socket.io" : "0.9.10",
        "ntwitter": "0.4.1"
    },
    "engines": {
        "node": "0.8.x",
        "npm": "1.1.49"
    }
}
```

Any help would be much much appreciate :)

Please not that using only console.log and removing the socket.io makes it work perfectly (didn't yet see a crash)

**Comment by fent** [comment]
From line 251 on `lib/twitter.js` it looks like trying to open a twitter stream gives an HTTP error.

Also unrelated but if all of the streams you open will track the same thing regardless of user connecting, just open one stream and broadcast to all users from that.

**Comment by gabrielstuff** [comment]
`Also unrelated but if all of the streams you open will track the same thing regardless of user connecting, just open one stream and broadcast to all users from that.`

Hey, you are totally right, actually I would much prefere to push the unique stream to all user any time the twitter stream got something.

About `lib/twitter.js` causing the error, what should I do ?

**Comment by fent** [comment]
Always listen to the `error` event from streams, and from event emitters that might emit it. In this case, listen to it, read what it says. It's probably something with your credentials.

If not, might have something to do with twitter recently updating their API to v1.1, in which case the URLs this module uses would need to be updated.

**Comment by gabrielstuff** [comment]
Well, the app is working sometime, and sometime not.
To me (from the C++ world) it looks like memory error or stuff like that.
Credential are fine, as I frequently get all the tweet I want.

When you say you want me to listen to error, do you mind that it is mandatory ? if so, why all the example does not show it ? or am I missing something ?

Thank you,

**Comment by fent** [comment]
The error is being emitted from when ntwitter tries to open the stream. My guess would be that it's working sometimes because the first few streams you open connect without problems and after a while you'll get rate limited since you never close the previous streams.

I'm also not positive but I think socket.io should give an error if you try to `socket.emit()` on a closed connection.

It's not in the examples because the node API for event emitters already say that you should always listen for possible `error` events, else they will be thrown.

**Comment by gabrielstuff** [comment]
looks pretty straightforward. Going to add the error handling part, which means I have to add it for socket.io AND twitter, right ?

Also, would you mind guide me about streaming the twitter data from one stream and broadcast that to user instead of opening the stream each time I got a connection.

Thank,

**Comment by fent** [comment]
I'm not sure socket.io emits any `error` events. It usually just emits when users connect/disconnect. It might emit errors although I've never encountered one.

Which is a bit inconsistent to what I just said. Just read the API on the modules, they should say if they emit `error` events.

to emit to all socket.io connected users

``` js
t.stream(
    'statuses/filter',
    { track: ['awesome', 'cool', 'rad', 'gnarly', 'groovy'] },
    function(stream) {
        stream.on('data', function(tweet) {
            //console.log(tweet.text);
            new_tweet = tweet.text;
            io.sockets.emit('new_tweet', new_tweet);
        });
    }
);
```

**Comment by gabrielstuff** [comment]
Well, after reading and learning, I say lets close that issue :)

Thank for your grateful help !
