### ISSUE TITLE
updateStatus fails if the tweet contains an apostrophe

### ISSUE THREAD

**Issue by michielbdejong** [AvianFlu/ntwitter#89]
presumably all tweets that contain apostrophes fail. With the demo code from http://www.catonmat.net/blog/nodejs-modules-ntwitter/  i replace:

```
.updateStatus('Test tweet from ntwitter/' + twitter.VERSION,
```

with:

```
.updateStatus('test \' ',
```

and then i get:

Tweeting failed: Error: HTTP Error 401: Unauthorized, API message: {"errors":[{"message":"Could not authenticate you","code":32}]}

(note this is not verifyCredentials reporting this error, but updateStatus, and if i tweet without apostrophes, then it works)

I npm-installed ntwitter two days ago, so i'm using version 0.2.8 (on a Debian server).

For now i will avoid using apostrophes in my tweets :)

**Comment by fent** [comment]
Dupe of #74

**Comment by michielbdejong** [comment]
oops! thanks.
